[{ name: "Osvaldo Alonso",
              position: "Midfielder"},
              {name: "Stefan Frei",
              position: "Goalkeeper"},
              {name: "Tyrone Mears",
              position: "Defender"},
              {name: "Brad Evans",
              position: "Midfielder"},
              {name: "Chad Marshall",
              position: "Defender"},
              {name: "Leonardo Gonzalez",
              position: "Defender"},
              {name: "Lamar Neagle",
              position: "Midfielder/Forward"},
              {name: "Gonzalo Pineda",
              position: "Midfielder"},
              {name: "Micheal Azira",
              position: "Midfielder"},
              {name: "Marco Pappa",
              position: "Midfielder"},
              {name: "Clint Dempsey",
              position: "Forward"},
              {name: "Obafemi Martins",
              position: "Forward"}];
